version: '3.7'

services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    expose:
      - 6379
    volumes:
      - ./redis-data:/data
    command: redis-server
    networks:
      - redis
  app:
    image: xsmas29/ms-surya-bumantara-betest:1.0
    working_dir: /ms-surya-bumantara-betest
    networks:
      - redis
    volumes:
      - .:/ms-surya-bumantara-betest
    ports:
      - 3030:3030
    depends_on:
      - redis
    command: ["npm", "run", "start"]
networks:
  redis:
    driver: bridge